# -*- coding: utf-8 -*-
"""Copy of Crime Rate Prediction using Facebook Prophet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fyOrzzJFaQ4W4yLOVEbf4D55ZQMts4t0
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
import plotly.express as px
from fbprophet import Prophet

data =pd.read_csv('crime_merged.csv', index_col = [0]) 

df = data[['ID','Date','Primary Type','Location Description','Arrest','Domestic','Zipcode']]

df.Date = pd.to_datetime(df.Date,format = '%m/%d/%Y %I:%M:%S %p')
df.index = pd.DatetimeIndex(df.Date)

df_prophet = pd.DataFrame(df[df['Primary Type']=='BATTERY'].resample('M').size().reset_index())

df_prophet.columns =['Date','Crime Count']

df_prophet=df_prophet.rename(columns={'Date':'ds','Crime Count':'y'})

m = Prophet()
m.fit(df_prophet)


pred=m.make_future_dataframe(periods=12,freq='M')
forecast = m.predict(pred)


plot = px.line(forecast,x="ds",y="yhat")

st.plotly_chart(plot, use_container_width = True)

incident_option = st.selectbox("Type of Incident", tuple(set(df["Primary Type"])))
st.write(incident_option)

zipcode_option = st.selectbox("Area", tuple(set(df['Zipcode'])))
st.write(zipcode_option)

